# declare base image and working directory of the container
FROM node:18
WORKDIR /app

# copy files to docker container from the host
COPY . /app

# install node modules inside container
RUN npm install

# Expose container port 5225, deafult protocol is TCP
EXPOSE 3000

# start the node express application
CMD ["npm", "start"]