name: Build and deploy application container on Azure Web App

env:
    AZURE_WEBAPP_NAME:   # TODO add app name

on: workflow_dispatch # only allow manual deployment

permissions:
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
